all: \
  Output/Debug/Obj/lab5_jc\
  Output/Debug/Exe\
  Output/Debug/Exe/lab5_jc.elf\

Output/Debug/Obj/lab5_jc:
	mkdir -p "Output/Debug/Obj/lab5_jc"
Output/Debug/Exe:
	mkdir -p "Output/Debug/Exe"

-include Output/Debug/Obj/lab5_jc/system_stm32l4xx.d
Output/Debug/Obj/lab5_jc/system_stm32l4xx.o:STM32L4xx/Device/Source/system_stm32l4xx.c
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -mtp=soft -mfp16-format=ieee -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/system_stm32l4xx.d -MQ Output/Debug/Obj/lab5_jc/system_stm32l4xx.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -mtext=.init -mrodata=.init_rodata -fshort-enums -fno-common /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Source/system_stm32l4xx.c -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/system_stm32l4xx.asm -Wuninitialized
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/system_stm32l4xx.asm -o Output/Debug/Obj/lab5_jc/system_stm32l4xx.o
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/system_stm32l4xx.asm

-include Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.d
Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.o:../lib/STM32L432KC_FLASH.c
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -mtp=soft -mfp16-format=ieee -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.d -MQ Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/jordancarlin/e155/e155-lab5/mcu/lib/STM32L432KC_FLASH.c -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.asm -Wuninitialized
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.asm -o Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.o
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.asm

-include Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.d
Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.o:../lib/STM32L432KC_GPIO.c
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -mtp=soft -mfp16-format=ieee -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.d -MQ Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/jordancarlin/e155/e155-lab5/mcu/lib/STM32L432KC_GPIO.c -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.asm -Wuninitialized
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.asm -o Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.o
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.asm

-include Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.d
Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.o:../lib/STM32L432KC_RCC.c
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -mtp=soft -mfp16-format=ieee -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.d -MQ Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/jordancarlin/e155/e155-lab5/mcu/lib/STM32L432KC_RCC.c -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.asm -Wuninitialized
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.asm -o Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.o
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.asm

-include Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.d
Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.o:../lib/STM32L432KC_SPI.c
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -mtp=soft -mfp16-format=ieee -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.d -MQ Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/jordancarlin/e155/e155-lab5/mcu/lib/STM32L432KC_SPI.c -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.asm -Wuninitialized
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.asm -o Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.o
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.asm

-include Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.d
Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.o:../lib/STM32L432KC_TIM.c
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -mtp=soft -mfp16-format=ieee -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.d -MQ Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/jordancarlin/e155/e155-lab5/mcu/lib/STM32L432KC_TIM.c -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.asm -Wuninitialized
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.asm -o Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.o
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.asm

-include Output/Debug/Obj/lab5_jc/STM32L432KC_USART.d
Output/Debug/Obj/lab5_jc/STM32L432KC_USART.o:../lib/STM32L432KC_USART.c
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -mtp=soft -mfp16-format=ieee -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_USART.d -MQ Output/Debug/Obj/lab5_jc/STM32L432KC_USART.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/jordancarlin/e155/e155-lab5/mcu/lib/STM32L432KC_USART.c -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_USART.asm -Wuninitialized
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_USART.asm -o Output/Debug/Obj/lab5_jc/STM32L432KC_USART.o
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L432KC_USART.asm

-include Output/Debug/Obj/lab5_jc/button_interrupt.d
Output/Debug/Obj/lab5_jc/button_interrupt.o:../src/button_interrupt.c
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -mtp=soft -mfp16-format=ieee -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/button_interrupt.d -MQ Output/Debug/Obj/lab5_jc/button_interrupt.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/jordancarlin/e155/e155-lab5/mcu/src/button_interrupt.c -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/button_interrupt.asm -Wuninitialized
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/button_interrupt.asm -o Output/Debug/Obj/lab5_jc/button_interrupt.o
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/button_interrupt.asm

-include Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup.d
Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup.o:SEGGER_THUMB_Startup.s
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -lang-asm -fdiagnostics-color=never -fdiagnostics-show-caret -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup.d -MQ Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup.o -quiet /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/SEGGER_THUMB_Startup.s -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup_PP.s
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup_PP.s -o Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup.o -g -gdwarf-4
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup_PP.s

-include Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors.d
Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors.o:STM32L4xx/Source/stm32l432xx_Vectors.s
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -lang-asm -fdiagnostics-color=never -fdiagnostics-show-caret -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors.d -MQ Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors.o -quiet /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Source/stm32l432xx_Vectors.s -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors_PP.s
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors_PP.s -o Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors.o -g -gdwarf-4
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors_PP.s

-include Output/Debug/Obj/lab5_jc/STM32L4xx_Startup.d
Output/Debug/Obj/lab5_jc/STM32L4xx_Startup.o:STM32L4xx/Source/STM32L4xx_Startup.s
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -lang-asm -fdiagnostics-color=never -fdiagnostics-show-caret -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -nostdinc "-isystem/Applications/SEGGER/SEGGER Embedded Studio 8.16a/include" -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=81601 -DDEBUG -DARM_MATH_CM4 -DSTM32L432xx -D__STM32L432_SUBFAMILY -D__STM32L4XX_FAMILY -MD /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L4xx_Startup.d -MQ Output/Debug/Obj/lab5_jc/STM32L4xx_Startup.o -quiet /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Source/STM32L4xx_Startup.s -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L4xx_Startup_PP.s
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/gcc/arm-none-eabi/bin/as" --traditional-format -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/CMSIS_5/CMSIS/Core/Include -I/Users/jordancarlin/e155/e155-lab5/mcu/lib -I/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L4xx_Startup_PP.s -o Output/Debug/Obj/lab5_jc/STM32L4xx_Startup.o -g -gdwarf-4
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm" -f /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Obj/lab5_jc/STM32L4xx_Startup_PP.s

Output/Debug/Exe/lab5_jc.elf:\
  Output/Debug/Obj/lab5_jc/system_stm32l4xx.o\
  Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.o\
  Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.o\
  Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.o\
  Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.o\
  Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.o\
  Output/Debug/Obj/lab5_jc/STM32L432KC_USART.o\
  Output/Debug/Obj/lab5_jc/button_interrupt.o\
  Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup.o\
  Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors.o\
  Output/Debug/Obj/lab5_jc/STM32L4xx_Startup.o\
  /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx_Flash.icf
	"/Applications/SEGGER/SEGGER Embedded Studio 8.16a/bin/segger-ld" --add-region:FLASH1=0x00040000@0x08000000 --add-region:RAM1=0x00004000@0x10000000 --add-region:RAM2=0x0000c000@0x20000000 --full-section-headers --merge-sections --merge-strings --map-text --map-file=Output/Debug/Exe/lab5_jc.map --map-standard -eReset_Handler -EL -mcpu=7E-M --silent --list-all-undefineds -T/Users/jordancarlin/e155/e155-lab5/mcu/segger_project/STM32L4xx_Flash.icf --defsym=__STACKSIZE__=2048 --defsym=__STACKSIZE_PROCESS__=0 --defsym=__HEAPSIZE__=1024 --defsym=__SEGGER_RTL_vfprintf=__SEGGER_RTL_vfprintf_int_nwp --defsym=__SEGGER_RTL_vfscanf=__SEGGER_RTL_vfscanf_int -u_vectors -o /Users/jordancarlin/e155/e155-lab5/mcu/segger_project/Output/Debug/Exe/lab5_jc.elf Output/Debug/Obj/lab5_jc/system_stm32l4xx.o Output/Debug/Obj/lab5_jc/STM32L432KC_FLASH.o Output/Debug/Obj/lab5_jc/STM32L432KC_GPIO.o Output/Debug/Obj/lab5_jc/STM32L432KC_RCC.o Output/Debug/Obj/lab5_jc/STM32L432KC_SPI.o Output/Debug/Obj/lab5_jc/STM32L432KC_TIM.o Output/Debug/Obj/lab5_jc/STM32L432KC_USART.o Output/Debug/Obj/lab5_jc/button_interrupt.o Output/Debug/Obj/lab5_jc/SEGGER_THUMB_Startup.o Output/Debug/Obj/lab5_jc/stm32l432xx_Vectors.o Output/Debug/Obj/lab5_jc/STM32L4xx_Startup.o "/Applications/SEGGER/SEGGER Embedded Studio 8.16a/lib/libc_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a" "/Applications/SEGGER/SEGGER Embedded Studio 8.16a/lib/SEGGER_crtinit_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a" "/Applications/SEGGER/SEGGER Embedded Studio 8.16a/lib/prinops_rtt_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a" "/Applications/SEGGER/SEGGER Embedded Studio 8.16a/lib/heapops_basic_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a" "/Applications/SEGGER/SEGGER Embedded Studio 8.16a/lib/heapops_disable_interrupts_locking_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a" "/Applications/SEGGER/SEGGER Embedded Studio 8.16a/lib/strops_unaligned_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a" "/Applications/SEGGER/SEGGER Embedded Studio 8.16a/lib/mbops_timeops_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a"